<?php

namespace Database\Seeders;

use App\Models\Page;
use App\Models\SiteSetting;
use App\Support\ContentSchema;
use App\Support\PageLocales;
use Illuminate\Database\Seeder;

/**
 * Makes sure every editable page exists (including the hidden "site" page that
 * holds the header, footer and shared blocks) and stores all page content in the
 * database: English from ContentSchema, Khmer from data/khmer-content.php.
 * Never overwrites content that is already saved.
 *
 * Run on its own with: php artisan db:seed --class=SiteContentSeeder
 */
class SiteContentSeeder extends Seeder
{
    /** slug => [English title, Khmer title, route name, menu group] */
    private const PAGES = [
        'home' => ['Home', 'ទំព័រដើម', 'frontend.home', 'main'],
        'about-us' => ['About', 'អំពីយើង', 'frontend.about-us', 'main'],
        'history' => ['History', 'ប្រវត្តិ', 'frontend.history', 'main'],
        'product' => ['Our Program', 'កម្មវិធីរបស់យើង', 'frontend.product', 'main'],
        'jobs-announcement' => ['Jobs Announcement', 'ដំណឹងជ្រើសរើសបុគ្គលិក', 'frontend.page', 'resources'],
        'annual-report' => ['Annual Report', 'របាយការណ៍ប្រចាំឆ្នាំ', 'frontend.page', 'resources'],
        'strategic-plan' => ['Strategic Plan', 'ផែនការយុទ្ធសាស្ត្រ', 'frontend.page', 'resources'],
        'partner' => ['Partner', 'ដៃគូ', 'frontend.page', 'resources'],
        'volunteer' => ['Volunteer', 'ស្ម័គ្រចិត្ត', 'frontend.page', 'involved'],
        'image-gallery' => ['Image', 'រូបភាព', 'frontend.gallery', 'involved'],
        'video' => ['Video', 'វីដេអូ', 'frontend.page', 'involved'],
        'contact' => ['Contact', 'ទំនាក់ទំនង', 'frontend.contact', 'hidden'],
        'donate' => ['Donate', 'បរិច្ចាគ', 'frontend.donate', 'hidden'],
        ContentSchema::SITE => ['Website: header, footer & shared blocks', '', null, 'hidden'],
    ];

    public function run(): void
    {
        $nextSortOrder = (Page::max('sort_order') ?? 0) + 1;
        $siteName = trim((string) SiteSetting::get('site_name', ''));
        $khmer = require __DIR__ . '/data/khmer-content.php';

        foreach (self::PAGES as $slug => [$title, $khmerTitle, $routeName, $menuGroup]) {
            $page = Page::where('slug', $slug)->first();

            if (!$page) {
                $isSite = $slug === ContentSchema::SITE;
                $page = Page::create([
                    'slug' => $slug,
                    'title' => $title,
                    'route_name' => $routeName,
                    'menu_group' => $menuGroup,
                    'is_active' => true,
                    'sitemap_include' => !$isSite && $slug !== 'donate',
                    'sort_order' => $isSite ? $nextSortOrder + 500 : $nextSortOrder++,
                    'translations' => ['en' => ['title' => $title, 'content' => '']],
                ]);
                $this->command?->info("Created page: {$slug}");
            }

            // Fill the Khmer menu title when it is missing or still a copy of the English one.
            if ($khmerTitle !== '') {
                $translations = $page->translations ?? [];
                $englishTitle = $translations['en']['title'] ?? $page->title;
                $currentKhmer = trim((string) ($translations['km']['title'] ?? ''));
                if ($currentKhmer === '' || $currentKhmer === $englishTitle) {
                    $translations['km'] = ['title' => $khmerTitle, 'content' => $translations['km']['content'] ?? ''];
                    $page->update(['translations' => $translations]);
                }
            }

            // Clear SEO text generated by the old template ("<site name> | …") so the
            // browser title follows the design ("About | Bandos Komar Organization").
            if ($siteName !== '' && str_starts_with((string) $page->meta_title, $siteName . ' | ')) {
                $page->update(['meta_title' => null, 'meta_description' => null, 'og_tags' => null]);
            }

            $this->storeContent($page, $khmer[$slug] ?? []);
        }

        // The site settings page must never show up as a public page.
        Page::where('slug', ContentSchema::SITE)->update(['menu_group' => 'hidden', 'sitemap_include' => false]);

        $this->command?->info('Editable website pages are ready.');
    }

    /**
     * Save every field into the database: English gets the built-in content for any field
     * not saved yet, Khmer gets the translations for any text still empty.
     * Values already saved (for example from the admin) are kept.
     */
    private function storeContent(Page $page, array $khmer): void
    {
        $fields = ContentSchema::fields($page->slug);
        $content = $page->page_content ?? [];
        if (!array_intersect(array_keys($content), PageLocales::all())) {
            $content = [PageLocales::default() => $content];
        }

        $english = $content['en'] ?? [];
        foreach ($fields as $key => $field) {
            if (!array_key_exists($key, $english)) {
                $english[$key] = $field['default'] ?? '';
            }
        }
        $content['en'] = $english;

        $translated = is_array($content['km'] ?? null) ? $content['km'] : [];
        foreach ($fields as $key => $field) {
            if ($field['type'] === 'list') {
                $current = array_filter((array) ($translated[$key] ?? []), fn ($item) => is_array($item) && array_filter($item, fn ($v) => trim((string) $v) !== ''));
                if (!$current && !empty($khmer[$key])) {
                    $translated[$key] = $khmer[$key];
                }
                continue;
            }
            if (!ContentSchema::isTranslatable($field) || trim((string) ($translated[$key] ?? '')) !== '') {
                continue;
            }
            $value = $khmer[$key] ?? $field['default_km'] ?? null;
            if ($value !== null) {
                $translated[$key] = $value;
            }
        }
        $content['km'] = $translated;

        $page->update(['page_content' => $content]);
    }
}
